version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 6672:5672
      - 16672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#  warehouse:
#    build: ./Warehouse
#    container_name: warehouse
#    environment:
#      - RABBITMQ_USER=guest
#      - RABBITMQ_PASS=guest
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
#    ports:
#      - 4344:3344
#      - 4355:3355
#    depends_on:
#      - rabbitmq
#  centralservice:
#    build: ./CentralService
#    container_name: centralservice
#    environment:
#      - RABBITMQ_USER=guest
#      - RABBITMQ_PASS=guest
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
#    depends_on:
#      - rabbitmq
volumes:
  rabbitmq_data: